export const SELECIONAR_CLIENTE = 'SELECIONAR_CLIENTE';
export const SELECIONAR_PRODUCTO = 'SELECIONAR_PRODUCTO';
export const CANTIDAD_PRODUCTOS = 'CANTIDAD_PRODUCTOS';
export const ACTUALIZAR_TOTAL = 'ACTUALIZAR_TOTAL';